services:
  proxy:
    image: proxy
    links:
      - identidock
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=10.0.1.6
      - NGINX_PROXY=http://identidock:9090
  identidock:
    image: alex1255/identidock:newest
    links:
      - dnmonster
      - redis
    environment:
      ENV: PROD
  dnmonster:
    image: amouat/dnmonster
  redis:
    image: redis