services:
  proxy:
    image: proxy
    links:
      - identidock
    ports:
      - "80:80"
  identidock:
    image: alex1255/identidock:newest
    links:
      - dnmonster
      - redis
    environment:
      ENV: PROD
  dnmonster:
    image: amouat/dnmonster
  redis:
    image: redis