services:
  proxy:
    image: alex1255/proxy:1.0
    links:
      - identidock
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=10.0.1.6
      - NGINX_PROXY=http://identidock:9090
  identidock:
    image: alex1255/identidock:1.0
    links:
      - dnmonster
      - redis
    environment:
      ENV: PROD
  dnmonster:
    image: amouat/dnmonster
  redis:
    image: redis
  logspout:
    image: amouat/logspout-logstash
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:90"