services:
  proxy:
    image: alex1255/proxy:1.0
    links:
      - identidock
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=10.0.1.6
      - NGINX_PROXY=http://identidock:9090
  identidock:
    image: alex1255/identidock:1.0
    links:
      - dnmonster
      - redis
    environment:
      ENV: PROD
  dnmonster:
    image: amouat/dnmonster
  redis:
    image: redis
  
  logstash:
    image: logstash:8.10.1
    volumes:
      - /home/unlo/identidock/logstash.conf:/etc/logstash/conf.d/logstash.conf
    environment:
      LOGSPOUT: ignore
      LOG_LEVEL: fatal
    command: -f /etc/logstash/conf.d/logstash.conf
  
  logspout:
    image: amouat/logspout-logstash
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - logstash
    environment:
      ROUTE_URIS: logstash://logstash:5000
      RETRY_STARTUP: "true"
    depends_on:
      - logstash
