services:
  logstash:
    image: logstash:8.10.2
    volumes:
      - /home/unlo/identidock/testelk/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./certs:/etc/logstash/certs:ro
    environment:
      LOG_LEVEL: error
      CONFIG_RELOAD_AUTOMATIC: true
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    
  elasticsearch:
    image: elasticsearch:8.10.2
    environment:
      discovery.type: single-node
      ELASTIC_PASSWORD: "12345"
    volumes:
      - ./certs/http_ca.crt:/etc/elasticsearch/certs/http_ca.crt
  
  kibana:
    image: kibana:8.10.2
    environment:
      ELASTICSEARCH_HOSTS: https://elasticsearch:9200
    links:
      - elasticsearch
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
