services:
#  logstash:
#    image: logstash:8.10.2
#    volumes:
#      - /home/unlo/identidock/testelk/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
#    environment:
#      LOG_LEVEL: error
#      CONFIG_RELOAD_AUTOMATIC: true
#    links:
#      - elasticsearch
#    depends_on:
#      - elasticsearch
    
  elasticsearch:
    image: elasticsearch:8.10.2
    environment:
      xpack.license.self_generated.type: basic
    volumes:
      - usr:/usr:ro

#  kibana:
#    image: kibana:8.10.2
#    environment:
#      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
#    links:
#      - elasticsearch
#    ports:
#      - "5601:5601"
#    depends_on:
#      - elasticsearch

volumes:
  usr: