services:
  logstash:
    image: logstash:8.10.2
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - /usr
    environment:
      LOG_LEVEL: error
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    
  elasticsearch:
    image: elasticsearch:8.10.2
    environment:
      discovery.type: single-node
      ELASTIC_PASSWORD: "12345"
    volumes:
      - /usr
  
  kibana:
    image: kibana:8.10.2
    environment:
      ELASTICSEARCH_HOSTS: https://elasticsearch:9200
    links:
      - elasticsearch
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
