services:
#  logstash:
#    image: logstash:8.10.2
#    volumes:
#      - /home/unlo/identidock/testelk/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
#    environment:
#      LOG_LEVEL: error
#      CONFIG_RELOAD_AUTOMATIC: true
#    links:
#      - elasticsearch
#    depends_on:
#      - elasticsearch
    
  elasticsearch:
    image: elasticsearch:8.10.2
    environment:
      XPACK.LICENSE.SELF__GENERATED_TYPE: basic
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"
      ELASTIC_PASSWORD: "12345"
      XPACK_SECURITY_ENABLED: true
      XPACK_SECURITY.AUTOCONFIGURATION.ENABLED: true
      DISCOVERY_TYPE: single-node
      XPACK_SECURITY_HTTP_SSL_ENABLED: true
    volumes:
      - certs:/usr/share/elasticsearch/config
    ports:
      - "9200:9200"

#  kibana:
#    image: kibana:8.10.2
#    environment:
#      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
#    links:
#      - elasticsearch
#    ports:
#      - "5601:5601"
#    depends_on:
#      - elasticsearch

volumes:
  certs: