services:
  logstash:
    image: logstash:8.10.2
    volumes:
      - /home/unlo/identidock/testelk/logstash.conf:/etc/logstash/conf.d/logstash.conf
    environment:
      LOG_LEVEL: warn
    links:
      - elasticsearch
    command: -f /etc/logstash/conf.d/logstash.conf
    depends_on:
      - elasticsearch
    
  elasticsearch:
    image: elasticsearch:8.10.2
    environment:
      discovery.type: single-node
      ELASTIC_PASSWORD: "12345"
    volumes:
      - dirs:/
  
  kibana:
    image: kibana:8.10.2
    environment:
      ELASTICSEARCH_HOSTS: https://elasticsearch:9200
    links:
      - elasticsearch
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
